#!/bin/sh

red="\033[1;31m"
green="\033[1;32m"
fg_reset="\033[0m"

error() {
  printf "%b\n" "${red}$1${fg_reset}" 1>&2
}

if ! command -v wget > /dev/null; then
    error "wget not found"
    exit 1
fi


tmp_dir=$(mktemp -d)
emoji_dir="$HOME"/.local/share/unicode
version=2.7

wget https://github.com/Mange/emoji-data/releases/download/v${version}/prebuilt-data-v${version}.tar.bz2 -P "$tmp_dir" || exit
cd "$tmp_dir"
tar -xf prebuilt-data-v${version}.tar.bz2
cd data || exit

mkdir -p "$emoji_dir"
cp * "$emoji_dir"

printf "%b\n" "${green}emojis successfully installed\!${fg_reset}" 1>&2
