#!/bin/sh

if [ ! "$NO_COLOR" = 1 ]; then
  red="\033[1;31m"
  fg_reset="\033[0m"
else
  red=""
  fg_reset=""
fi

error() {
  printf "%b\n" "${red}$1${fg_reset}"  2>&1
}

if ! command -v mew || ! command -v jq || ! command -v wl-copy; then
  error "dependencies are missing, please make sure jq, mew, and wl-copy are installed"
fi

# Give mew list of all unicode characters.
# Shows the selected character in notification daemon if running.
# Character is copied to system clipboard using wl-copy.

emoji_file=$HOME/.local/share/unicode/all_emojis.json

if [ ! -f "$emoji_file" ]; then
  error "emoji file not found, please install it using the emoji-gen script
  or build manually from https://github.com/Mange/emoji-data"
  exit
fi

emoji=$(jq -r ' .[] | "\(.characters) \(.en_tts_description)"' "$emoji_file" \
  | tr '[:upper:]' '[:lower:]' \
  | mew \
  | awk '{print $1}' \
  | tr -d '\n')


if [ ! "$emoji" = "" ] && grep "$emoji" "$emoji_file"; then
  echo "$emoji" | wl-copy
    notify-send "emoji: $emoji copied"
fi
